import type { Metadata } from "next";
import { Quicksand, Dancing_Script, Pacifico } from "next/font/google";
import { ThemeProvider as NextJSThemeProvider } from "next-themes";
import "./globals.css";
import { Toaster } from "sonner";
import { TRPCReactProvider } from "@/trpc/client";

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body
          className={`${quickSand.variable} ${dancingScript.variable} ${pacifico.variable} antialiased`}
        >
          <NextJSThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            <Toaster />
            {children}
          </NextJSThemeProvider>
        </body>
      </html>
    </TRPCReactProvider>
  );
}
